// Ultimate Procedural Map Generation System
// Copyright (C) 2025. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Async/AsyncWork.h"
#include "ProceduralMeshComponent.h"
#include "ThirdParty/FastNoiseLite/FastNoiseLite.h"

/**
 * Structure containing all mesh data generated by the terrain generation task
 * This data is generated on a background thread and then applied to the mesh on the game thread
 */
struct FTerrainMeshData
{
	/** Vertex positions for the procedural mesh */
	TArray<FVector> Vertices;

	/** Triangle indices defining mesh faces (3 indices per triangle) */
	TArray<int32> Triangles;

	/** Normal vectors for each vertex (used for lighting) */
	TArray<FVector> Normals;

	/** UV coordinates for texture mapping */
	TArray<FVector2D> UVs;

	/** Vertex colors (can be used for material effects or biome blending) */
	TArray<FColor> VertexColors;

	/** Tangent vectors for advanced material effects */
	TArray<FProcMeshTangent> Tangents;

	/** Default constructor */
	FTerrainMeshData()
	{
	}

	/** Reserve memory for expected vertex/triangle count to avoid reallocation */
	void Reserve(int32 ExpectedVertices, int32 ExpectedTriangles)
	{
		Vertices.Reserve(ExpectedVertices);
		Normals.Reserve(ExpectedVertices);
		UVs.Reserve(ExpectedVertices);
		VertexColors.Reserve(ExpectedVertices);
		Tangents.Reserve(ExpectedVertices);
		Triangles.Reserve(ExpectedTriangles * 3);
	}

	/** Clear all arrays */
	void Clear()
	{
		Vertices.Empty();
		Triangles.Empty();
		Normals.Empty();
		UVs.Empty();
		VertexColors.Empty();
		Tangents.Empty();
	}
};

/**
 * Parameters for terrain generation
 * Passed to the async task to configure how the terrain is generated
 */
struct FTerrainGenerationParams
{
	/** Size of the chunk in world units */
	float ChunkSize;

	/** Number of vertices per side (resolution) */
	int32 VerticesPerSide;

	/** Scale factor for noise sampling (smaller = more stretched terrain) */
	float NoiseScale;

	/** Multiplier for height values (vertical scale) */
	float ZMultiplier;

	/** World position offset for this chunk */
	FVector ChunkWorldPosition;

	/** Random seed for procedural generation */
	int32 Seed;

	/** LOD level (0 = highest detail) */
	int32 LODLevel;

	/** Number of octaves for fractal noise */
	int32 Octaves;

	/** Frequency of the base noise */
	float Frequency;

	/** Amplitude multiplier for each octave */
	float Lacunarity;

	/** Persistence (amplitude decay) for each octave */
	float Persistence;

	/** Default constructor with sensible defaults */
	FTerrainGenerationParams()
		: ChunkSize(1000.0f)
		, VerticesPerSide(100)
		, NoiseScale(0.001f)
		, ZMultiplier(500.0f)
		, ChunkWorldPosition(FVector::ZeroVector)
		, Seed(1337)
		, LODLevel(0)
		, Octaves(4)
		, Frequency(0.01f)
		, Lacunarity(2.0f)
		, Persistence(0.5f)
	{
	}
};

/**
 * Asynchronous task for generating terrain mesh data
 * Inherits from FNonAbandonableTask to ensure the task completes even if the game object is destroyed
 *
 * This task runs on a background thread pool and generates vertices, triangles, normals, and UVs
 * for a terrain chunk using FastNoiseLite for procedural noise generation.
 *
 * Usage:
 *   FAsyncTask<FTerrainGenerationTask>* Task = new FAsyncTask<FTerrainGenerationTask>(Params);
 *   Task->StartBackgroundTask();
 *   // ... later, check if done and retrieve results ...
 *   if (Task->IsDone())
 *   {
 *       FTerrainMeshData& MeshData = Task->GetTask().GetMeshData();
 *       // Apply to procedural mesh component
 *   }
 */
class FTerrainGenerationTask : public FNonAbandonableTask
{
	friend class FAsyncTask<FTerrainGenerationTask>;

public:
	/**
	 * Constructor
	 * @param InParams - Parameters for terrain generation
	 */
	FTerrainGenerationTask(const FTerrainGenerationParams& InParams)
		: Params(InParams)
		, bIsComplete(false)
	{
	}

	/**
	 * Get the generated mesh data (call this after the task is complete)
	 * @return Reference to the generated mesh data
	 */
	FTerrainMeshData& GetMeshData()
	{
		return MeshData;
	}

	/**
	 * Check if the task has completed
	 * @return True if generation is complete
	 */
	bool IsComplete() const
	{
		return bIsComplete;
	}

protected:
	/**
	 * Main work function - called on background thread
	 * Generates all mesh data for the terrain chunk
	 */
	void DoWork()
	{
		// Initialize FastNoiseLite with our parameters
		FastNoiseLite NoiseGenerator;
		NoiseGenerator.SetNoiseType(FastNoiseLite::NoiseType_OpenSimplex2);
		NoiseGenerator.SetSeed(Params.Seed);
		NoiseGenerator.SetFrequency(Params.Frequency);
		NoiseGenerator.SetFractalType(FastNoiseLite::FractalType_FBm);
		NoiseGenerator.SetFractalOctaves(Params.Octaves);
		NoiseGenerator.SetFractalLacunarity(Params.Lacunarity);
		NoiseGenerator.SetFractalGain(Params.Persistence);

		// Calculate actual vertices based on LOD
		const int32 LODMultiplier = FMath::Pow(2, Params.LODLevel);
		const int32 ActualVerticesPerSide = FMath::Max(2, Params.VerticesPerSide / LODMultiplier);
		const int32 TotalVertices = ActualVerticesPerSide * ActualVerticesPerSide;
		const int32 TotalTriangles = (ActualVerticesPerSide - 1) * (ActualVerticesPerSide - 1) * 2;

		// Pre-allocate arrays for better performance
		MeshData.Reserve(TotalVertices, TotalTriangles);

		// Calculate spacing between vertices
		const float VertexSpacing = Params.ChunkSize / (ActualVerticesPerSide - 1);

		// Generate vertices with height from noise
		for (int32 Y = 0; Y < ActualVerticesPerSide; Y++)
		{
			for (int32 X = 0; X < ActualVerticesPerSide; X++)
			{
				// Calculate local position
				const float LocalX = X * VertexSpacing;
				const float LocalY = Y * VertexSpacing;

				// Calculate world position for noise sampling
				const float WorldX = Params.ChunkWorldPosition.X + LocalX;
				const float WorldY = Params.ChunkWorldPosition.Y + LocalY;

				// Sample noise at this world position
				const float NoiseValue = NoiseGenerator.GetNoise(
					WorldX * Params.NoiseScale,
					WorldY * Params.NoiseScale
				);

				// Convert noise (-1 to 1) to height
				const float Height = NoiseValue * Params.ZMultiplier;

				// Add vertex
				MeshData.Vertices.Add(FVector(LocalX, LocalY, Height));

				// Generate UV coordinates (0 to 1 across the chunk)
				MeshData.UVs.Add(FVector2D(
					static_cast<float>(X) / (ActualVerticesPerSide - 1),
					static_cast<float>(Y) / (ActualVerticesPerSide - 1)
				));

				// Generate vertex color based on height (can be used for biome blending)
				const uint8 ColorValue = FMath::Clamp(
					static_cast<int32>((NoiseValue + 1.0f) * 127.5f),
					0,
					255
				);
				MeshData.VertexColors.Add(FColor(ColorValue, ColorValue, ColorValue, 255));
			}
		}

		// Generate triangles (two triangles per quad)
		for (int32 Y = 0; Y < ActualVerticesPerSide - 1; Y++)
		{
			for (int32 X = 0; X < ActualVerticesPerSide - 1; X++)
			{
				const int32 BottomLeft = Y * ActualVerticesPerSide + X;
				const int32 BottomRight = BottomLeft + 1;
				const int32 TopLeft = (Y + 1) * ActualVerticesPerSide + X;
				const int32 TopRight = TopLeft + 1;

				// First triangle (bottom-left, top-left, top-right)
				MeshData.Triangles.Add(BottomLeft);
				MeshData.Triangles.Add(TopLeft);
				MeshData.Triangles.Add(TopRight);

				// Second triangle (bottom-left, top-right, bottom-right)
				MeshData.Triangles.Add(BottomLeft);
				MeshData.Triangles.Add(TopRight);
				MeshData.Triangles.Add(BottomRight);
			}
		}

		// Generate normals for proper lighting
		GenerateNormals();

		// Generate tangents for advanced material effects
		GenerateTangents();

		bIsComplete = true;
	}

	/**
	 * Required by FNonAbandonableTask interface
	 * Used for stats tracking in Unreal's task system
	 */
	FORCEINLINE TStatId GetStatId() const
	{
		RETURN_QUICK_DECLARE_CYCLE_STAT(FTerrainGenerationTask, STATGROUP_ThreadPoolAsyncTasks);
	}

private:
	/** Generation parameters */
	FTerrainGenerationParams Params;

	/** Generated mesh data */
	FTerrainMeshData MeshData;

	/** Completion flag */
	bool bIsComplete;

	/**
	 * Calculate smooth normals for the mesh
	 * Uses face normals and averages them for each vertex
	 */
	void GenerateNormals()
	{
		// Initialize all normals to zero
		MeshData.Normals.SetNumZeroed(MeshData.Vertices.Num());

		// Calculate face normals and accumulate for each vertex
		for (int32 i = 0; i < MeshData.Triangles.Num(); i += 3)
		{
			const int32 Index0 = MeshData.Triangles[i];
			const int32 Index1 = MeshData.Triangles[i + 1];
			const int32 Index2 = MeshData.Triangles[i + 2];

			const FVector& V0 = MeshData.Vertices[Index0];
			const FVector& V1 = MeshData.Vertices[Index1];
			const FVector& V2 = MeshData.Vertices[Index2];

			// Calculate face normal using cross product
			const FVector Edge1 = V1 - V0;
			const FVector Edge2 = V2 - V0;
			const FVector FaceNormal = FVector::CrossProduct(Edge1, Edge2);

			// Accumulate for each vertex of this triangle
			MeshData.Normals[Index0] += FaceNormal;
			MeshData.Normals[Index1] += FaceNormal;
			MeshData.Normals[Index2] += FaceNormal;
		}

		// Normalize all normals
		for (FVector& Normal : MeshData.Normals)
		{
			Normal.Normalize();
		}
	}

	/**
	 * Generate tangent vectors for normal mapping support
	 * Tangents are perpendicular to normals and align with UV coordinates
	 */
	void GenerateTangents()
	{
		MeshData.Tangents.SetNum(MeshData.Vertices.Num());

		// Simple tangent generation based on UV coordinates
		for (int32 i = 0; i < MeshData.Vertices.Num(); i++)
		{
			// Create a tangent perpendicular to the normal
			FVector Tangent = FVector::CrossProduct(
				MeshData.Normals[i],
				FVector(0, 0, 1)
			);

			// If normal is too close to (0,0,1), use a different reference vector
			if (Tangent.SizeSquared() < 0.001f)
			{
				Tangent = FVector::CrossProduct(
					MeshData.Normals[i],
					FVector(0, 1, 0)
				);
			}

			Tangent.Normalize();
			MeshData.Tangents[i] = FProcMeshTangent(Tangent, false);
		}
	}
};
